dependencies {
    implementation project(":core:common-core")
    // Spring Cloud Gateway
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
    // Eureka Client for Service Discovery (Eureka 클라이언트)
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    implementation 'io.jsonwebtoken:jjwt-impl:0.12.6'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.12.6'
    // SpringDoc OpenAPI WebFlux UI (Swagger)
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.8.9'
    // Spring Boot Actuator
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    // Thymeleaf (HTML 템플릿 렌더링용)
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    // WebFlux
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
}
