dependencies {
    implementation project(":Module:common-module")
    implementation project(":Module:persistence-module")
    implementation project(":Module:security-module")
    implementation project(":Module:redis-module")

    // Spring Data JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // Spring MVC
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // MySQL JDBC
    runtimeOnly 'com.mysql:mysql-connector-j'
    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // Spring Security 기본 (FilterChain, @PreAuthorize 등)
    implementation 'org.springframework.boot:spring-boot-starter-security'
}