x-auth-service-environment: &auth_service_environment
  SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
  SPRING_APPLICATION_NAME: ${AUTH_SERVICE_APP_NAME}
  AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
  DB_URL: ${DB_URL}
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: ${REDIS_PORT}
  JWT_ACCESS_KEY: ${JWT_ACCESS_KEY}
  JWT_REFRESH_KEY: ${JWT_REFRESH_KEY}
  JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
  JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
  MINIO_URL: ${MINIO_URL}
  MINIO_BUCKET_PREFIX: ${MINIO_BUCKET_PREFIX}
  MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
  MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  SNOWFLAKE_DATACENTER_ID: ${SNOWFLAKE_DATACENTER_ID}
  SNOWFLAKE_WORKER_ID: ${SNOWFLAKE_WORKER_ID}
  SERVICE_DISCOVERY_HOST_NAME: ${SERVICE_DISCOVERY_HOSTNAME}
  SERVICE_DISCOVERY_PORT: ${SERVICE_DISCOVERY_PORT}

services:
  auth-service-dev:
    container_name: auth-service-dev
    build:
      context: .
      dockerfile: auth-service.Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT_DEV}:${AUTH_SERVICE_PORT}" # host:container
    environment:
      <<: *auth_service_environment
    networks:
      - 8llow8llowme-net

  auth-service-prod:
    container_name: auth-service-prod
    build:
      context: .
      dockerfile: auth-service.Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT_PROD}:${AUTH_SERVICE_PORT}" # host:container
    environment:
      <<: *auth_service_environment
    networks:
      - 8llow8llowme-net

networks:
  8llow8llowme-net:
    name: 8llow8llowme-net
    driver: bridge