rootProject.name = 'backend'

// Cores
include 'core:common-module'
include 'core:persistence-module'
include 'core:security-module'
include 'core:redis-module'
include 'core:storage-module'

// Services
include 'service:auth-service'
include 'service:trip-service'

// Spring Cloud
include 'cloud:api-gateway'
include 'cloud:service-discovery'