rootProject.name = 'backend'

// Cores
include 'core:common-core'
include 'core:persistence-core'
include 'core:security-core'
include 'core:redis-core'
include 'core:storage-core'

// Services
include 'service:auth-service'
include 'service:trip-service'
include 'service:batch-service'
include 'service:trip-game-service'
include 'service:monitoring-service'

// Spring Cloud
include 'cloud:api-gateway'
include 'cloud:service-discovery'