rootProject.name = 'backend'

// Modules
include 'Module:common-module'
include 'Module:persistence-module'
include 'Module:security-module'
include 'Module:redis-module'
include 'Module:storage-module'

// Services
include 'Service:auth-service'
include 'Service:trip-service'

// Spring Cloud
include 'Cloud:api-gateway'
include 'Cloud:service-discovery'