server:
  port: 8081
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tripmarble?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true       # 데이터베이스 URL
    username: ENC(OL9lhGYuBl819xoaLMPAxuTVlN8pJ3GE)
    password: ENC(Q7kGpk90tMWOMI0Eoa6+xqjXROMGqmTxIiKQvkZldzw=)

  jpa:
    open-in-view: true
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
        jdbc:
          batch_size: 1000
        default_batch_fetch_size: 100

# log 관리
logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      org.hibernate.SQLQuery: debug

# snowflake
snowflake:
  datacenter-id: 1
  worker-id: 1
