server:
  port: ${AUTH_SERVICE_PORT}
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false
        jdbc:
          batch_size: 100
        default_batch_fetch_size: 100

  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30 # 인스턴스가 헬스 체크 전송하는 주기 (안정적 갱신 주기, default: true)
    lease-expiration-duration-in-seconds: 90 # 인스턴스 만료 대기 시간 (운영에서는 너무 빠르게 내려가지 않도록)
  client:
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOSTNAME}:${SERVICE_DISCOVERY_PORT}/eureka/
    fetch-registry: true # 유레카 클라이언트가 유레카 서버로부터 인스턴스 레지스트리 주기적으로 받아올지 여부 (default: true)
    registry-fetch-interval-seconds: 30 # 레지스트리 몇 초마다 가져올지 (부하 줄이기, default: 30)
    initial-instance-info-replication-interval-seconds: 5 # 유레카 서버에 처음 등록할 때까지 대기 시간

# Snowflake
snowflake:
  datacenter-id: ${SNOWFLAKE_DATACENTER_ID}
  worker-id: ${SNOWFLAKE_WORKER_ID}

# JWT 설정
jwt:
  access-key: ${JWT_ACCESS_KEY}
  refresh-key: ${JWT_REFRESH_KEY}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

# Minio 설정
minio:
  internal-url: ${MINIO_INTERNAL_URL}
  public-url: ${MINIO_PUBLIC_URL}
  bucket-prefix: ${MINIO_BUCKET_PREFIX}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}

# Mail 설정
mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  smtp-auth: ${MAIL_SMTP_AUTH}
  starttls-enable: ${MAIL_STARTTLS_ENABLE}

# OAUTH 2.0
oauth:
  kakao:
    client-id: ${OAUTH_KAKAO_CLIENT_ID} # Rest API 키
    client-secret: ${OAUTH_KAKAO_CLIENT_SECRET}
    redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI}
    scope:
      - profile_nickname
      - profile_image
      - account_email
  #      - name # 사업자 정보 있어야 해당 정보 가져오기 가능

  naver:
    client-id: ${OAUTH_NAVER_CLIENT_ID} # Rest API 키
    client-secret: ${OAUTH_NAVER_CLIENT_SECRET}
    redirect-uri: ${OAUTH_NAVER_REDIRECT_URI}
    scope:
      - nickname
      - profile_image
      - email
      - name