dependencies {
    implementation project(":core:common-core")
    implementation project(":core:persistence-core")
    // Spring Data JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // Spring MVC
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // MySQL JDBC
    runtimeOnly 'com.mysql:mysql-connector-j'
    // Map Struct
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
}
