dependencies {
    implementation project(":core:common-core")
    implementation project(":core:persistence-core")
    implementation project(":core:security-core")
    implementation project(":core:storage-core")
    implementation project(":core:redis-core")

    // Spring Data JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // Spring MVC
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // MySQL JDBC
    runtimeOnly 'com.mysql:mysql-connector-j'
    // SpringDoc (swagger - openapi 3.0)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.6'
    // Eureka Client for Service Discovery (Eureka 클라이언트)
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    // Map Struct
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    // 안전한 QueryDSL 버전 (OpenFeign 포크 사용)
    implementation 'io.github.openfeign.querydsl:querydsl-jpa:6.11'
    annotationProcessor 'io.github.openfeign.querydsl:querydsl-apt:6.11:jpa'
    // Spring Security Resource Server
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    // Feign Client
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // MinIO
    implementation 'io.minio:minio:8.5.17'
    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
}
