dependencies {
    implementation project(":core:common-core")
    implementation project(":core:persistence-core")
    // Spring Data JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // Spring MVC
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // MySQL JDBC
    runtimeOnly 'com.mysql:mysql-connector-j'
}
