server:
  port: 8082
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tripmarble?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true       # 데이터베이스 URL
    username: ENC(OL9lhGYuBl819xoaLMPAxuTVlN8pJ3GE)
    password: ENC(Q7kGpk90tMWOMI0Eoa6+xqjXROMGqmTxIiKQvkZldzw=)

  jpa:
    open-in-view: true
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
        jdbc:
          batch_size: 100
        default_batch_fetch_size: 100

  servlet:
    multipart:
      max-file-size: 30MB # 파일 하나당 최대 30MB
      max-request-size: 150MB # 요청 전체 합계 (30MB * 5개)

  data:
    redis:
      mode: standalone
      host: localhost
      port: 6379
      password:

# log 관리
logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      org.hibernate.SQLQuery: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Swagger
swagger:
  server-url: http://localhost:8000

# Snowflake
snowflake:
  datacenter-id: 1
  worker-id: 1

# Security Resource Server
security:
  oauth2:
    resource-server:
      jwt:
        access-key: ENC(YDO9DGO7lP8iCqeTNW/SXWCv0697ep+bbGvMnjoJfMDEtWy1Zq/yfZDsovoggEcmLLOtZfHSpLYoRO0YEUlrOl3CvD5KWXo55haCMx7cZMg=)

# minio
minio:
  internal-url: http://localhost:9000
  public-url: http://localhost:9000
  bucket-prefix: tripmarble
  access-key: ENC(fkrxtIidUHN1LoxCucgcFpBXqSh22NiO)
  secret-key: ENC(gyy+d4BkG2lphHopsii2hNLjUHutcbZNZcev8D90M08=)