dependencies {
    // Jasypt (Java Simplified Encryption)
    implementation 'com.github.ulisesbocchio:jasypt-spring-boot-starter:3.0.5'
    // SpringDoc (swagger - openapi 3.0)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.6'
}

jar { enabled = true }
bootJar { enabled = false }