dependencies {
    // 공통 설정 관련
    implementation project(":core:common-core")
    // Spring MVC
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // JWT 기반 인증을 위한 Resource Server 기능 (JwtAuthenticationConverter 등)
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    // Spring Security 기본 (FilterChain, @PreAuthorize 등)
    implementation 'org.springframework.boot:spring-boot-starter-security'
    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'
}

jar { enabled = true }
bootJar { enabled = false }