import { GameSummary } from "@/entities/games/hooks/useMyGameList";

export const myGamesDummy: GameSummary[] = [
  {
    tripGameId: "611541051487948800",
    gameStatus: "ONGOING",
    gameStatusDescription: "게임 진행 중",
    difficultyCode: "NORMAL",
    difficultyDescription: "보통",
    representativeRegionImageUrl: null,
    representativeRegionName: "제주",
    title: "여름 제주도 여행1123333",
    startedAt: "2025-08-19",
    endedAt: "2025-08-20",
    tripThemeNames: ["관광", "전시", "축제/공연", "액티비티"],
    isHost: true,
    isReady: true,
  },
  {
    tripGameId: "611539779464597504",
    gameStatus: "WAITING",
    gameStatusDescription: "게임 시작 전",
    difficultyCode: "EASY",
    difficultyDescription: "쉬움",
    representativeRegionImageUrl: null,
    representativeRegionName: "경주",
    title: "최성호",
    startedAt: "2025-08-18",
    endedAt: "2025-08-21",
    tripThemeNames: ["축제/공연"],
    isHost: true,
    isReady: true,
  },
  {
    tripGameId: "609394784645287936",
    gameStatus: "WAITING",
    gameStatusDescription: "게임 시작 전",
    difficultyCode: "EASY",
    difficultyDescription: "쉬움",
    representativeRegionImageUrl: null,
    representativeRegionName: "서울",
    title: "12123",
    startedAt: "2025-08-11",
    endedAt: "2025-08-14",
    tripThemeNames: ["축제/공연"],
    isHost: true,
    isReady: true,
  },
  {
    tripGameId: "607898286812172288",
    gameStatus: "WAITING",
    gameStatusDescription: "게임 시작 전",
    difficultyCode: "EASY",
    difficultyDescription: "쉬움",
    representativeRegionImageUrl: null,
    representativeRegionName: "강릉",
    title: "1",
    startedAt: "2025-08-16",
    endedAt: "2025-08-20",
    tripThemeNames: ["쇼핑"],
    isHost: true,
    isReady: true,
  },
  {
    tripGameId: "607893924220112896",
    gameStatus: "WAITING",
    gameStatusDescription: "게임 시작 전",
    difficultyCode: "HARD",
    difficultyDescription: "어려움",
    representativeRegionImageUrl: null,
    representativeRegionName: "여수",
    title: "123123",
    startedAt: "2025-08-12",
    endedAt: "2025-08-22",
    tripThemeNames: ["축제/공연"],
    isHost: true,
    isReady: true,
  },
  {
    tripGameId: "606737436579598336",
    gameStatus: "WAITING",
    gameStatusDescription: "게임 시작 전",
    difficultyCode: "EASY",
    difficultyDescription: "쉬움",
    representativeRegionImageUrl: null,
    representativeRegionName: "서울",
    title: "123",
    startedAt: "2025-08-12",
    endedAt: "2025-08-15",
    tripThemeNames: ["관광", "전시"],
    isHost: true,
    isReady: true,
  },
  {
    tripGameId: "606737091170275328",
    gameStatus: "WAITING",
    gameStatusDescription: "게임 시작 전",
    difficultyCode: "NORMAL",
    difficultyDescription: "보통",
    representativeRegionImageUrl: null,
    representativeRegionName: "제주",
    title: "여름 제주도 여행",
    startedAt: "2025-08-15",
    endedAt: "2025-08-20",
    tripThemeNames: ["관광", "전시", "축제/공연", "액티비티"],
    isHost: true,
    isReady: true,
  },
];
