server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: trip-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/trip-spots/**, /api/v1/trip-content-types

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  access-key: ENC(YDO9DGO7lP8iCqeTNW/SXWCv0697ep+bbGvMnjoJfMDEtWy1Zq/yfZDsovoggEcmLLOtZfHSpLYoRO0YEUlrOl3CvD5KWXo55haCMx7cZMg=)