server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        # Swagger 문서용 라우트
        - id: auth-service-docs
          uri: http://localhost:8081
          predicates:
            - Path=/auth-service/** # /auth-service/v3/api-docs 로 들어오면
          filters:
            - StripPrefix=1  # /v3/api-docs 로 잘라서 전달
        - id: trip-service-docs
          uri: http://localhost:8082
          predicates:
            - Path=/trip-service/**
          filters:
            - StripPrefix=1
        - id: trip-game-service-docs
          uri: http://localhost:8083
          predicates:
            - Path=/trip-game-service/**
          filters:
            - StripPrefix=1
        # 에러코드 조회용 라우트
        - id: internal-auth-service-error-codes
          uri: http://localhost:8081
          predicates:
            - Path=/internal/auth-service/error-codes # Gateway로 들어오는 경로
          filters:
            - RewritePath=/internal/auth-service/error-codes, /internal/v1/error-codes # Auth Service로 전달할 경로
        - id: internal-trip-service-error-codes
          uri: http://localhost:8082
          predicates:
            - Path=/internal/trip-service/error-codes # Gateway로 들어오는 경로
          filters:
            - RewritePath=/internal/trip-service/error-codes, /internal/v1/error-codes # Auth Service로 전달할 경로
        - id: internal-trip-game-service-error-codes
          uri: http://localhost:8083
          predicates:
            - Path=/internal/trip-game-service/error-codes # Gateway로 들어오는 경로
          filters:
            - RewritePath=/internal/trip-game-service/error-codes, /internal/v1/error-codes # Auth Service로 전달할 경로
          # 기존 API 라우트
        - id: trip-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/regions/**, /api/v1/trip-spots/**, /api/v1/trip-content-types/**, /api/v1/me/reviews/**
        - id: trip-game-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/trip-themes/**, /api/v1/trip-games/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  access-key: ENC(YDO9DGO7lP8iCqeTNW/SXWCv0697ep+bbGvMnjoJfMDEtWy1Zq/yfZDsovoggEcmLLOtZfHSpLYoRO0YEUlrOl3CvD5KWXo55haCMx7cZMg=)

# SpringDoc (Swagger) Aggregation
springdoc:
  swagger-ui:
    # Swagger UI 활성화 여부
    enabled: true
    # Swagger UI 접근 경로
    path: /swagger-ui.html
    # Swagger UI 구성에 대한 URL
    config-url: /v3/api-docs/swagger-config
    # 각 서비스의 OpenAPI 문서 URL 목록
    urls:
      - name: 회원 서비스 및 인증/인가 관련 API
        url: /auth-service/v3/api-docs
      - name: 지역 및 여행 서비스 관련 API
        url: /trip-service/v3/api-docs
      - name: 여행 게임(계획) 서비스 관련 API
        url: /trip-game-service/v3/api-docs
    operationsSorter: none # API 정렬 기준 없음
    displayRequestDuration: true # 각 API 요청의 응답시간(ms) 표시

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,info" # 해당 actuator endpoint 노출
  endpoint:
    health:
      show-details: ALWAYS # SBA에서 상세 health 정보까지 보기 위함