server:
  port: ${API_GATEWAY_PORT}
  shutdown: graceful

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Swagger 문서용 라우트
        - id: auth-service-docs
          uri: lb://AUTH-SERVICE-DEV
          predicates:
            - Path=/auth-service/** # /auth-service/v3/api-docs 로 들어오면
          filters:
            - StripPrefix=1 # /v3/api-docs 로 잘라서 전달
        - id: trip-service-docs
          uri: lb://TRIP-SERVICE-DEV
          predicates:
            - Path=/trip-service/**
          filters:
            - StripPrefix=1
        - id: trip-game-service-docs
          uri: lb://TRIP-GAME-SERVICE-DEV
          predicates:
            - Path=/trip-game-service/**
          filters:
            - StripPrefix=1
        # 에러코드 조회용 라우트
        - id: internal-auth-service-error-codes
          uri: lb://AUTH-SERVICE-DEV
          predicates:
            - Path=/internal/auth-service/error-codes # Gateway로 들어오는 경로
          filters:
            - RewritePath=/internal/auth-service/error-codes, /internal/v1/error-codes # Auth Service로 전달할 경로
        - id: internal-trip-service-error-codes
          uri: lb://TRIP-SERVICE-DEV
          predicates:
            - Path=/internal/trip-service/error-codes # Gateway로 들어오는 경로
          filters:
            - RewritePath=/internal/trip-service/error-codes, /internal/v1/error-codes # Auth Service로 전달할 경로
        - id: internal-trip-game-service-error-codes
          uri: lb://TRIP-GAME-SERVICE-DEV
          predicates:
            - Path=/internal/trip-game-service/error-codes # Gateway로 들어오는 경로
          filters:
            - RewritePath=/internal/trip-game-service/error-codes, /internal/v1/error-codes # Auth Service로 전달할 경로
        # 기존 API 라우트
        - id: trip-service
          uri: lb://TRIP-SERVICE-DEV
          predicates:
            - Path=/api/v1/regions/**, /api/v1/trip-spots/**, /api/v1/trip-content-types/**, /api/v1/me/reviews/**
          filters:
            - JwtAuthApiGatewayFilter
        - id: trip-game-service
          uri: lb://TRIP-GAME-SERVICE-DEV
          predicates:
            - Path=/api/v1/trip-themes/**, /api/v1/trip-games/**
          filters:
            - JwtAuthApiGatewayFilter

eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5 # 인스턴스가 헬스 체크 전송하는 주기
    lease-expiration-duration-in-seconds: 10 # 인스턴스 만료 대기 시간
  client:
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOSTNAME}:${SERVICE_DISCOVERY_PORT}/eureka/
    fetch-registry: true # 유레카 클라이언트가 유레카 서버로부터 인스턴스 레지스트리 주기적으로 받아올지 여부 (default: true)
    registry-fetch-interval-seconds: 3 # 레지스트리 몇 초마다 가져올지
    initial-instance-info-replication-interval-seconds: 5 # 유레카 서버에 처음 등록할 때까지 대기 시간

jwt:
  access-key: ${JWT_ACCESS_KEY}

springdoc:
  swagger-ui:
    # Swagger UI 활성화 여부
    enabled: true
    # Swagger UI 접근 경로
    path: /swagger-ui.html
    # Swagger UI 구성에 대한 URL
    config-url: /v3/api-docs/swagger-config
    # 각 서비스의 OpenAPI 문서 URL 목록
    urls:
      - name: 회원 서비스 및 인증/인가 관련 API
        url: /auth-service/v3/api-docs
      - name: 지역 및 여행 서비스 관련 API
        url: /trip-service/v3/api-docs
      - name: 여행 게임(계획) 서비스 관련 API
        url: /trip-game-service/v3/api-docs
    operationsSorter: none # API 정렬 기준 없음
    displayRequestDuration: true # 각 API 요청의 응답시간(ms) 표시